header_pages:
  - pages/about.md
  - pages/season-one.md
  - pages/faq.md
  - pages/handbook.md
  - pages/alumni.md
  - pages/testimonials.md
  - pages/notes.md

markdown: kramdown
title: Codershigh
email: sudarshan@iitrpr.ac.in
description: >-
  A discussion-first learning community for algorithms, computer science,
  and deep collaborative thinking. Codershigh values slow reasoning,
  conceptual clarity, and collective intellectual adventure over speed.
baseurl: /codershigh/ # the subpath of your site, e.g. /blog
url: https://sudarshansudarshan.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sudarshaniisc
github_username:  sudarshansudarshan

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - backup/
  - ver1/
  - ver2/
  - _internal/
  - scripts/
timezone: Asia/Kolkata

collections:
  case_studies:
    output: true
    permalink: /case-studies/:slug/
